### ISSUE TITLE
Ошибка получения оценок

### ISSUE THREAD

**Issue by TerminalPR0** [mezhendosina/sgo-app#24]
Проблем с интернетом нет, не загружает оценки, видео приложено.
https://we.tl/t-h3gcOEGgG3

**Comment by mezhendosina** [comment]
Скорее всего это связано с отключением старого способа получения оценок. Я уже работаю над этим, но конкретных дат сказать не смогу

**Comment by TerminalPR0** [comment]
Буду ждать новых коммитов, спасибо

**Comment by mezhendosina** [comment]
Починил вот здесь: 2157670c53946e926a03e8e84e576935ad294286
